### ISSUE TITLE
Troubles setting up a virtual audio device for use with Bluetooth

### ISSUE THREAD

**Issue by Axieum** [scottlawsonbc/audio-reactive-led-strip#151]
I see that this supports a "virtual audio device", but am struggling to set this up for use with my current Bluetooth audio setup.

As of now, I have the LED working with the `strandtest.py`, and I also have my Bluetooth audio playing through the 3.5mm audio jack! Great.

Now, I wish to have this `visualization.py` read data from the Bluetooth audio input, and I believe I should be setting it up with Jack2 or something, but am really unsure of how to go about this.

Any help is much appreciated!

**Comment by Axieum** [comment]
This is the current log I am getting.

```
pi@raspberrypi:~ $ sudo python audio-reactive-led-strip/python/visualization.py
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'cards.bcm2835_alsa.pcm.front.0:CARD=0'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:5007:(snd_config_expand) Evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM front
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.iec958
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
ALSA lib confmisc.c:1281:(snd_func_refer) Unable to find definition 'defaults.bluealsa.device'
ALSA lib conf.c:4528:(_snd_config_evaluate) function snd_func_refer returned error: No such file or directory
ALSA lib conf.c:4996:(snd_config_expand) Args evaluate error: No such file or directory
ALSA lib pcm.c:2495:(snd_pcm_open_noupdate) Unknown PCM bluealsa
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
JackShmReadWritePtr::~JackShmReadWritePtr - Init not done for -1, skipping unlock
No audio input. Volume below threshold. Volume: 9.97921e-17
No audio input. Volume below threshold. Volume: 0.0
```

**Comment by Axieum** [comment]
Okay, update, I've managed to setup a `Loopback` and set it to the default audio device. Changing the `microphone.py` channels from 1 to 2, and running it has it waiting for audio input. But the moment I hit play on my phone, it immediately raises an exception:

```
Traceback (most recent call last):
  File "visualization.py", line 358, in <module>
    microphone.start_stream(microphone_update)
  File "/home/pi/Audio_Reactive_LED_Strip/python/microphone.py", line 21, in start_stream
    callback(y)
  File "visualization.py", line 199, in microphone_update
    y_roll[-1, :] = np.copy(y)
ValueError: could not broadcast input array from shape (1470) into shape (735)
```
