### ISSUE TITLE
LED strip reactivity falling significantly behind audio...

### ISSUE THREAD

**Issue by Axieum** [scottlawsonbc/audio-reactive-led-strip#152]
My current setup is Bluetooth audio input, which it detects the audio, but as it plays, the delay gets longer and longer as though it is falling behind significantly.

I can pause the song, and have to wait up to 16 seconds before the animation finishes. Letting them go dark, and playing the music again, results in another massive wait before the LEDs light up.

I am using a Raspberry Pi 3 (Model B+) with Raspbian Stretch.

Note, that in order for me to initially get the script to run, I had to tweak the `microphone.py` file such that it opens a PyAudio instance with `channels=2`. After this, I had issues with size mismatches:
```
Traceback (most recent call last):
  File "visualization.py", line 358, in <module>
    microphone.start_stream(microphone_update)
  File "/home/pi/Audio_Reactive_LED_Strip/python/microphone.py", line 21, in start_stream
    callback(y)
  File "visualization.py", line 199, in microphone_update
    y_roll[-1, :] = np.copy(y)
ValueError: could not broadcast input array from shape (1470) into shape (735)
```

I fixed this by changing the following lines in `visualization.py`:
```
y = audio_samples / 2.0**15
```
to (NB: essentially making sure it is of size 735 and not 1470):
```
y = (audio_samples / 2.0**15)[:735]
```

I am unsure whether this has an effect on the "history" or something, since, the longer the script is running, the further the animation seems to fall behind.

**Comment by Axieum** [comment]
Okay, so the 735 size, seems to be linked to the FPS and the PyAudio unit (`paInt32`).

By lowering the FPS down to 24, I was able to get a reasonably smooth LED that doesn't fall behind. I guess the Pi just isn't powerful enough.
