### ISSUE TITLE
Cannot install pyaudio

### ISSUE THREAD

**Issue by Kronoskrk** [scottlawsonbc/audio-reactive-led-strip#153]
Hi,
i followed the instructions till the start of the visualisation script.
I dragged the visualization.py file in the anaconda prompt and here is the code:

```
(visualization-env) C:\Users\...>"C:\Users\....\Documents\Projekt_LED_Visualizer\audio-reactive-led-strip-master\python\visualization.py"
Traceback (most recent call last):
  File "C:\Users\…\Documents\Projekt_LED_Visualizer\audio-reactive-led-strip-master\python\visualization.py", line 7, in <module>
    import microphone
  File "C:\Users\….\Documents\Projekt_LED_Visualizer\audio-reactive-led-strip-master\python\microphone.py", line 3, in <module>
    import pyaudio
ImportError: No module named pyaudio
```
                                      
It looks like pyaudio is not installed but in the env folder i found the pyaudio.py.
I tried "conda install pyaudio" and as a result it said that the package is not available from the current channels.
What can i do to get pyaudio?

Thanks for your help :)

**Comment by Kronoskrk** [comment]
I solved it.
There was an issue with Version of pyaudio and anaconda. So i simply installed the latest anaconda and create a environment without python=3.5.
Now it works.
