### ISSUE TITLE
N_PIXELS limit

### ISSUE THREAD

**Issue by rbirkby** [scottlawsonbc/audio-reactive-led-strip#26]
Any value over 250 throws, not 255:

```
pi@raspberrypi:~/src/audio-reactive-led-strip/python $ sudo python visualization.py
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.rear
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.center_lfe
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.side
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.hdmi
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.modem
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
ALSA lib pcm.c:2239:(snd_pcm_open_noupdate) Unknown PCM cards.pcm.phoneline
Cannot connect to server socket err = No such file or directory
Cannot connect to server request channel
jack server is not running or cannot be started
Traceback (most recent call last):
  File "visualization.py", line 344, in <module>
    microphone.start_stream(microphone_update)
  File "/home/pi/src/audio-reactive-led-strip/python/microphone.py", line 13, in start_stream
    callback(stream)
  File "visualization.py", line 218, in microphone_update
    led.update()
  File "/home/pi/src/audio-reactive-led-strip/python/led.py", line 140, in update
    _update_pi()
  File "/home/pi/src/audio-reactive-led-strip/python/led.py", line 102, in _update_pi
    if np.array_equal(p[:, i], _prev_pixels[:, i]):
IndexError: index 250 is out of bounds for axis 1 with size 250
```

```bash
pi@raspberrypi:~/src/audio-reactive-led-strip/python $ grep -ir N_PIXELS *
config.py:N_PIXELS = 251
```

I have a 5m strip with 300 pixels I'd quite like to get working

**Comment by scottlawsonbc** [comment]
The Pi should be able to run any number of pixels. 251 pixels throws an error because it is an odd number of pixels. What happens if you use 252?

**Comment by rbirkby** [comment]
Thanks - 300 pixels are working for me.
