### ISSUE TITLE
What does this mean?

### ISSUE THREAD

**Issue by Ratbagdoo** [scottlawsonbc/audio-reactive-led-strip#294]
Sketch uses 701562 bytes (53%) of program storage space. Maximum is 1310720 bytes.
Global variables use 40696 bytes (12%) of dynamic memory, leaving 286984 bytes for local variables. Maximum is 327680 bytes.
esptool.py v2.6
Serial port COM3
Traceback (most recent call last):
  File "esptool.py", line 2959, in <module>
  File "esptool.py", line 2952, in _main
  File "esptool.py", line 2652, in main
  File "esptool.py", line 222, in __init__
  File "site-packages\serial\__init__.py", line 88, in serial_for_url
  File "site-packages\serial\serialwin32.py", line 62, in open
serial.serialutil.SerialException: could not open port 'COM3': WindowsError(2, 'The system cannot find the file specified.')
Failed to execute script esptool
the selected serial port Failed to execute script esptool
 does not exist or your board is not connected

**Comment by joeybab3** [comment]
Sounds like you haven't selected the correct com port in the Arduino menu.
Check which port your Arduino is on in the device manager and change it to the correct one in the Arduino IDE.
