### ISSUE TITLE
led.py not detecting neopixel

### ISSUE THREAD

**Issue by sophialucille** [scottlawsonbc/audio-reactive-led-strip#313]
I am working on a raspberry pi 3+ and I had everything working perfectly until I got to running 'visualization.py'. I tested everything with the 'strandtest.py' from rpi_ws281x and it worked perfectly. However, when I try to run 'visualization.py', I get the error:
`Traceback (most recent call last):
     File "visualization.py", line 9, in <module>
          import led
     File "/home/pi/audio-reactive-led-strip-master/python/led.py", line 15, in <module>
          strip = neopixel.Adafruit_NeoPixel(config.N_PIXELS, config.LED_PIN,
AttributeError: module 'neopixel' has no attribute 'Adafruit_NeoPixel'`

Everything is downloaded and run through Python 3.7.3
Not sure what this could be as the library was linking up just fine for the strandtest which calls on neopixel. The 'audio-reactive-led-strip', 'adafruit-circuitpython-bundle-6' and 'rpi_ws281x' all reside in the 'home' folder

Please let me know if I need to add anymore information to aid in support

**Comment by wangwy1015** [comment]
把rpi_ws281x/python/neopixel.py拷贝到audio-reactive-led-strip/python/ 中即可解决~~
cp /path/../rpi_ws281x/python/neopixel.py /path/../audio-reactive-led-strip/python/
python visualization.py
和版本无关

**Comment by jraypdx** [comment]
Ran in to the same problem, thanks wangwy1015 for the help.

To clarify what they mean, in your audio-reactive-led-strip/python directory, create a new neopixel.py file and copy the contents from here:
https://raw.githubusercontent.com/jgarff/rpi_ws281x/master/python/neopixel.py

I'm not actually sure if the neopixel libraries need to be installed through pip, but I am able to run visualization.py using "sudo python3 visualization.py" and I had run the neopixel installation commands earlier, from here:
https://learn.adafruit.com/neopixels-on-raspberry-pi/python-usage

**Comment by kylerobert425** [comment]
having this same issue now, is there a new fix for this? the link to the contents for the neopixel.py linked above is dead so just curious what to do

**Comment by jraypdx** [comment]
@kylerobert425 try out this one, I think it's the same file:

https://github.com/richardghirst/rpi_ws281x/blob/master/python/neopixel.py

**Comment by kylerobert425** [comment]
Ok yup that works, thanks!
