### ISSUE TITLE
Unable to run the develop branch

### ISSUE THREAD

**Issue by kvchen** [scottlawsonbc/audio-reactive-led-strip#41]
I realize that the `develop` branch is still under progress, but I thought I'd give it a shot. Unfortunately, it doesn't look like it's working with my Raspberry Pi setup:

```
import audioled

audio, fs = audioled.stream_audio(chunk_rate=60)
effect = audioled.effects.spectrum(pixels=144, fs=fs, chunk_rate=60)

device = audioled.devices.RaspberryPi(pixels=144, pin=18, invert_logic=False, freq=800000, dma=5)

for pixels in effect(audio):
    device.show(pixels)
```

I get the following error:

```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    for pixels in effect(audio):
  File "/home/pi/audio-reactive-led-strip/audioled/effects.py", line 62, in effect
    audio, fs_ds = dsp.preprocess(audio, fs, fmax, n_overlaps)
  File "/home/pi/audio-reactive-led-strip/audioled/dsp.py", line 196, in preprocess
    audio = pad_zeros(audio)
  File "/home/pi/audio-reactive-led-strip/audioled/dsp.py", line 121, in pad_zeros
    peek = next(signal)
  File "/home/pi/audio-reactive-led-strip/audioled/dsp.py", line 195, in <genexpr>
    audio = (x for x in audio if np.sqrt(np.mean(np.square(x))) > 1e-5)
  File "/home/pi/audio-reactive-led-strip/audioled/dsp.py", line 194, in <genexpr>
    audio = (x * hanning_window for x in audio)
ValueError: operands could not be broadcast together with shapes (490,) (245,)
```

It looks like in `dsp.py`, the `rollwin` function is messing something up:

```
def rollwin(signal, n_overlaps):
    frame = next(signal)
    N = len(frame)
    window = np.zeros(N * n_overlaps)
    window[-N:] = frame

    for data in signal:
        window[:-N] = window[N:]
        window[-N:] = data
        yield window
```

The first time the `signal` generator is called, frame is of size 245. The next time it's iterated over (in the for loop), the size increases to 490. As far as I can tell, it keeps switching between the two. Any ideas?

**Comment by scottlawsonbc** [comment]
Thanks for the report. I'll look into this as soon as I can, but unfortunately due to final exams I won't be able to do so until next week.
