### ISSUE TITLE
Help with Raspi 1

### ISSUE THREAD

**Issue by ThinkEnigmatic** [scottlawsonbc/audio-reactive-led-strip#50]
Thank you for your time and effort to make this project. I have been successful running this project on my Raspi 3, but when I try to do the same on Raspi 1, I have the following issues regardless of which GPIO I try to set it to. I believe on the Rpi 1 the only choice for PWM is GPIO18 so I am frankly baffled by the error. I appreciate your help resolving this:
Gpio 18 is illegal for LED channel 0
Traceback (most recent call last):
  File "visualization.py", line 9, in <module>
    import led
  File "/home/pi/LED/python/led.py", line 18, in <module>
    strip.begin()
  File "build/bdist.linux-armv6l/egg/neopixel.py", line 115, in begin
RuntimeError: ws2811_init failed with code -11 (Selected GPIO not possible)
munmap error
: Invalid argument

**Comment by joeybab3** [comment]
Try a recent code revision and let me know if you are still having the problem.

**Comment by joeybab3** [comment]
Closing due to inactivity
